// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_HmSuVGvVGOFSN_OA4NbDcBDNJo6prKk',
    appId: '1:966590811927:web:6431fc221ab5ed16a6b152',
    messagingSenderId: '966590811927',
    projectId: 'ticket-avion',
    authDomain: 'ticket-avion.firebaseapp.com',
    storageBucket: 'ticket-avion.appspot.com',
    measurementId: 'G-NXHER96QQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUQf4HvyjAl-Tf01K3X6ItcP5G9VCOFQM',
    appId: '1:966590811927:android:64997ee282cd067aa6b152',
    messagingSenderId: '966590811927',
    projectId: 'ticket-avion',
    storageBucket: 'ticket-avion.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_HmSuVGvVGOFSN_OA4NbDcBDNJo6prKk',
    appId: '1:966590811927:web:8106dc36d3fc787ba6b152',
    messagingSenderId: '966590811927',
    projectId: 'ticket-avion',
    authDomain: 'ticket-avion.firebaseapp.com',
    storageBucket: 'ticket-avion.appspot.com',
    measurementId: 'G-WR0SXXCC9F',
  );
}
